### ISSUE TITLE
Name change

### ISSUE THREAD

**Issue by leostera** [leostera/transporter.io#10]
It just occurred to me that since we have multiple transports, it would make total sense to call the library transporter rather than dispatcher. I might have made a mistake and I apologize in advance if I did but...
- Rule 1: "Never change the deal”.
- Rule 2: "No names”.
- Rule 3: "Never open the package”.

As silly as it might sound, I immediately found the relations and thought it was not only a good way to establish sort of a brand but also to set some ideals for what we are making here:
- Rule 1: Once a package is sent: reconnect, retry, queue and make sure a package is delivered.
- Rule 2: Sender and receiver agnostic. Connect anywhere, deliver everywhere.
- Rule 3: Built-in crypto/bson security.

What do you think? @danielyoung @AndresAbed @simonwjackson 

I’m assigning this to @simonwjackson as he most likely would come up with a cool brand for it when the time comes.

**Comment by simonwjackson** [comment]
:+1:
